name: mediaai_personalization
version: "1.0"
config-version: 2

profile: default

model-paths: ["models"]

target-path: "target"

log-path: "logs"

test-paths: ["tests"]

analysis-paths: ["analyses"]

macro-paths: ["macros"]

seed-paths: ["seeds"]